[package]
name = "nerf-dart"
version = "0.1.0"
edition = "2024"
license = "MIT"
keywords = ["nerf-dart","nerf","dart","nerf-dart"]
repository = "https://github.com/SamTV12345/nerf-dart"
readme = "README.md"

[dependencies]
url = "*"
